apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubApp
spec:
  selector:
    matchLabels:
      app: myGithubapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myGithubapp
    spec:
      containers:
      - name: myGithubappContainer
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080
